services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-php
    volumes:
      - laravel_caddy:/app
    restart: unless-stopped
    expose:
      - '9000'
    networks:
      - caddy_net
      - laravel_db

  db:
    image: postgres:15
    container_name: laravel-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - '5434:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel_db

networks:
  laravel_db:
    driver: bridge
  caddy_net:
    external: true

volumes:
  pgdata:
  laravel_caddy:
    external: true
