name: Deploy PHP Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Installer Python et Ansible
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip
          pip3 install ansible

      - name: Ajouter la clé SSH pour Ansible
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 83.228.199.184 >> ~/.ssh/known_hosts

      - name: Lancer playbook Ansible
        run: ansible-playbook -i ./deploy/host.ini ./deploy/deploy.yaml
